version: '3'
services: 
  frontend:
    container_name: memosys-frontend
    build: ./frontend
    tty: true
    stdin_open: true
    ports:
      - 4000:4000
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c 'yarn install && yarn start'
  backend:
    container_name: api-server
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/go/src/backend
    tty: true
  database:
    image: mysql:8.0
    container_name: memosys-db
    environment:
        MYSQL_ROOT_PASSWORD: "light"
        MYSQL_DATABASE: "memosys-db"
        MYSQL_USER: "admin"
        MYSQL_PASSWORD: "project443"
        TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    tty: true
    stdin_open: true
    volumes:
        - ./database/data:/var/lib/mysql
    ports:
        - 3306:3306

